vo=gpu-next
hwdec=auto-copy

fs

profile=high-quality

#scale=catmull_rom
#dscale=catmull_rom

#sharpen=2

volume-max=200

scale=ewa_lanczos4sharpest
#cscale=ewa_lanczos4sharpest
dscale=ewa_lanczos4sharpest

#interpolation=yes
#tscale=oversample
video-sync=display-resample

save-position-on-quit

audio-pitch-correction=no

ytdl-format=bestvideo[height<=144]+bestaudio/best

#ytdl-format=bestvideo+bestaudio
