# ACTUAL PERSONAL CONFIGURATION

vo=gpu
hwdec=auto-copy

fs

profile=high-quality

sharpen=2

volume-max=200

#scale=ewa_lanczos4sharpest
#cscale=ewa_lanczos4sharpest
#dscale=ewa_lanczos4sharpest

interpolation=yes  # Enable frame interpolation
tscale=oversample  # Best for smooth motion
video-sync=display-resample  # Best sync method

save-position-on-quit

audio-pitch-correction=no

ytdl-format=bestvideo[height<=480]+bestaudio/best

#ytdl-format=bestvideo+bestaudio

