vo=gpu
#vo=gpu-next
hwdec=no
#hwdec=vaapi
#hwdec=vaapi-copy
gpu-api=opengl
video-sync=display-resample
profile=fast
fs
#ytdl-format=bestvideo[vcodec][height<=1080]+bestaudio/best
ytdl-format=bestvideo[vcodec^=avc1][height<=1080]+bestaudio/best
